---
- name: enable ip forwarding
  sysctl: name=net.ipv4.ip_forward value=1 state=present

- name: install shorewall packages
  package: name=shorewall state=present

- name: enable shorewall service
  service: name=shorewall enabled=yes

- name: enable shorewall startup
  lineinfile: dest=/etc/default/shorewall
              line='startup=1'
              regexp='^startup=.*'
              state=present
  notify: restart shorewall

- name: configure shorewall
  copy: src={{ item }} dest=/etc/shorewall/
  with_items:
  - interfaces
  - policy
  - rules
  - masq
  - tcdevices
  - tcclasses
  - mangle
  - accounting
  notify: restart shorewall
